
name: Build and Test GlassFish 5.1 App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t glassfish5-app .

      - name: Run container (optional test)
        run: docker run -d -p 8080:8080 glassfish5-app
